# Server config
server:
  port: 9093

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

info:
  component: API Gateway

# Spring config
spring:
  application:
    name: api-gateway

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    registerWithEureka: false



# Zuul config
zuul:
 #prefix: /api
  routes:
    articles:
      path: /oauth/**
      serviceId: oauth-service
    authors:
      path: /api/orders/**
      serviceId: order-service
 endpoints:
  routes:
   sensitive: false
  trace:
   sensitive: false