server:
 port: 9093
    
eureka:
 instance:
  hostname: localhost
  port: 9091
 client:
  registerWithEureka: true
  fetchRegistry: false
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
 server:
  wait-time-in-ms-when-sync-empty: 3000

zuul:
  routes:
    oauth-service:
      path: /oauth/**
      serviceId: oauth-service
    orders-service:
      path: /api/orders/**
      serviceId: orders-service
spring:
  application:
    name: gateway
