# Server config
server:
  port: 9093

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

info:
  component: API Gateway

# Spring config
spring:
  application:
    name: api-gateway

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    registerWithEureka: false

# Ribbon config http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
ribbon:
  eureka:
    enabled: true

# Zuul config
zuul:
 #prefix: /api
  routes:
   sensitive: false
   articles:
    path: /oauth/**
    serviceId: oauth-service
   authors:
     path: /api/orders/**
     serviceId: order-service