server:
 port: 9093
    
eureka:
 instance:
  hostname: localhost
  port: 9091
 client:
  registerWithEureka: true
  fetchRegistry: false
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
 server:
  wait-time-in-ms-when-sync-empty: 3000

zuul:
  routes:
    oauth-service:
      path: /oauth/**
      serviceId: oauth-service
    orders-service:
      path: /api/orders/**
      serviceId: orders-service
spring:
  application:
    name: gateway
    



# Server config
server:
  port: 9093

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

info:
  component: API Gateway

# Spring config
spring:
  application:
    name: api-gateway

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    registerWithEureka: false

